### ISSUE TITLE
Have you tested this against lockdown reverting to NSUserDefaults when installing/uninstalling a developer logging profile?

### ISSUE THREAD

**Issue by dlevi309** [kabiroberai/AllYourLogsAreBelongToMe#1]
This is cool, the only issue that may arise is when installing a logging profile from the Apple dev center [https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios](url) the plist that filters the system logs (com.apple.system.logging) is either changed to the “locked” filter or is reverted to NSUserDefaults when uninstalling a logging profile which deletes the com.apple.system.logging.plist altogether

**Comment by kabiroberai** [comment]
Those edge cases aren't really in scope for this project tbh, it's just a toy utility I decided to make because I thought that automating the process would be neat. In situations like the ones you mentioned, you could probably reinstall the package to fix things.
